### ISSUE TITLE
SpigotMC v1.21.2

### ISSUE THREAD

**Issue by EHCanadian** [cricri211/PsudoCommands#4]
`[Server thread/ERROR]: Error occurred while enabling PsudoCommand v1.0.37 (Is it up to date?)
java.lang.IllegalArgumentException: object of type net.minecraft.commands.CommandListenerWrapper is not an instance of net.minecraft.commands.CommandDispatcher
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:198) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.zombie_striker.psudocommands.PsudoReflection.getCommandDispatcher(PsudoReflection.java:217) ~[?:?]
	at me.zombie_striker.psudocommands.PsudoCommands.onEnable(PsudoCommands.java:29) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579) ~[spigot-1.21.2-R0.1-SNAPSHOT.jar:4349-Spigot-a084d85-d50f505]
	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493) ~[spigot-1.21.2-R0.1-SNAPSHOT.jar:4349-Spigot-a084d85-d50f505]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21.2-R0.1-SNAPSHOT.jar:4349-Spigot-a084d85-d50f505]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032) ~[spigot-1.21.2-R0.1-SNAPSHOT.jar:4349-Spigot-a084d85-d50f505]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.2-R0.1-SNAPSHOT.jar:4349-Spigot-a084d85-d50f505]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]`

**Comment by chrisgdt** [comment]
With the Paper hardfork of Spigot, I will drop the support for Spigot. Maybe the issue is resolved now, as the newest version also supports Spigot. Can you check it ?

**Comment by EHCanadian** [comment]
Yup, v1.0.38 works again on Spigot v1.21.4

Apricated.
